language: bash

sudo: required

services:
  - docker

install:
  - docker build -t ai-notebook .
  - docker run -d -p 127.0.0.1:8888:8888 --name ai-notebook ai-notebook

script:
  - docker ps | grep -q ai-notebook
